apiVersion: v1
kind: Namespace
metadata:
  name: atw-production
  labels:
    name: atw-production
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: atw-quota
  namespace: atw-production
spec:
  hard:
    requests.cpu: "10000"
    requests.memory: 10Ti
    persistentvolumeclaims: "1000"
    pods: "10000"
